### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### Frege/frege now has a Chat Room on Gitter

@YoEight has just created a chat room. You can visit it here: [https://gitter.im/Frege/frege](https://gitter.im/Frege/frege?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/Frege/frege?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by YoEight** [comment]
I thought it would be great for our user to be able to IM for question or anything else.

**Comment by Dierk** [comment]
Great thing - whereas, we also have the freenode chat under https://freenode.net/ . 
As long as the community is small enough, it may be good to have only one such that newcomers are less likely to find an empty room. So the question is: which one?

**Comment by YoEight** [comment]
I believe newcommers would prefer `gitter` but that just my opinion. `gitter` also support a wide range of notifications out of the box. Looking at the archives is also simpler and better

**Comment by ForNeVeR** [comment]
Yeah. I'm visiting IRC chat on freenode but I don't know if that's possible to read logs of this chat :(

BTW, gitter has IRC gateway too.

**Comment by seancorfield** [comment]
I've never heard of Gitter. I've heard of IRC. Freenode is where nearly all open source languages have a presence. Slack is becoming common for teams and has an IRC gateway so I'd say freenode IRC is the common denominator here. Frege's IRC channel is just starting to get traction -- I wouldn't want to dilute it. My vote would be "no" for Gitter. I certainly don't want to run another IM client!

**Comment by ForNeVeR** [comment]
Well, at first, you don't need _another one_. As I said, it supports in-browser and IRC clients both (in fact, I don't think you can get some specialized IM client for it - browser is enough as a start, and you may switch to any standard IRC client I think). And gitter also has a huge community (in my personal view, it's bigger and more popular than Slack). For example, see [DefinitelyTyped](https://gitter.im/borisyankov/DefinitelyTyped), [Scala](https://gitter.im/scala/scala) or [Scala.js](https://gitter.im/scala-js/scala-js) rooms. And gitter is more friendly to newcomers indeed (they don't need to set up IRC client etc - just visit the URL and start chatting).

So I'd say that gitter today is a popular discussion platform - as IRC or even better for some (maybe not all) projects. And it can become _another_ good place to discuss Frege.

BTW, where are logs of Frege IRC room? I have some difficulties finding them, and logs are important feature for such a low-traffic room as ours.

**Comment by seancorfield** [comment]
We'd need to run a logging bot on #frege to store logs somewhere. Most of the IRC channels I'm on don't seem to bother with logs.

Right now the #frege logs wouldn't be worth anything because people who pop in to ask questions don't hang around long enough for anyone to answer them. People need to idle/lurk more instead of popping in and out when it suits them :)

After looking at Gitter, I think it would be worth doing only if someone is willing and able to run the Node.js-based bot that synchronizes between Frege/frege on Gitter and #frege on freenode so that folks can go to whichever place they're most comfortable and not miss out on any chatter.

**Comment by seancorfield** [comment]
BTW, "I don't think you can get some specialized IM client for it" -- yup, it has desktop and mobile clients for most platforms.

**Comment by ForNeVeR** [comment]
My bad, I didn't know that.

**Comment by ForNeVeR** [comment]
Well, we can run or even develop such a bot with Frege ;) Can you direct me to some docs if you lurked it already?

**Comment by seancorfield** [comment]
I posted the link to the IRC bot in Gitter :)

**Comment by seancorfield** [comment]
Having spent some time with Gitter today and connecting to it via IRC, I'm withdrawing my objection. I think adding Gitter would be beneficial on balance. In particular, I like the GitHub integration that can show all activity from any of the Frege repos directly inside Gitter.

**Pull request merged**
