### PR TITLE
fixed #323

### LINKED ISSUE #323: Problems with Function being returned?
I want to implement the following:

```
class Arrow a => ArrowApply a where
    app :: a (a b c, b) c

instance ArrowApply (->) where
    app (f, b) = f b
```

but I get this error during the Java compilation step:

```
error: incompatible types: U<TTuple2<U<?,?>,?>,?> cannot be converted to B<U<?,?>,TTuple
2<B<U<?,?>,?,?>,?>,?>
        >app().call();
                   ^
  where ?,? are type-variables:
    ? extends Object declared in method <?,?>âapp()
    ? extends Object declared in method <?,?>âapp()
1 error
```

This is due to this code being wrongly generated:

```
final public static class IArrowApply_$minus$gt implements CArrowApply<Func.U<?, ?>> {
  public IArrowApply_$minus$gt() {}
  final public static IArrowApply_$minus$gt it = new IArrowApply_$minus$gt();
  @Override final public <𝓒, 𝓑> Kind.B<Func.U<?, ?>, PreludeBase.TTuple2<Kind.B<Func.U<?, ?>, 𝓑, 𝓒>, 𝓑>, 𝓒> ƒapp() {
    return (Kind.B<Func.U<?, ?>, PreludeBase.TTuple2<Kind.B<Func.U<?, ?>, 𝓑, 𝓒>, 𝓑>, 𝓒>)IArrowApply_$minus$gt.<
          𝓒, 𝓑
        >app().call();
  }
//...
  final public static <α, β> Lazy<Func.U<PreludeBase.TTuple2<Func.U<β, α>, β>, α>> app() {
    return (Func.U<PreludeBase.TTuple2<Func.U<β, α>, β>, α>)((final Lazy<PreludeBase.TTuple2<Func.U<β, α>, β>> arg$8203) -> {
              final PreludeBase.TTuple2<Func.U<β, α>, β> $8204 = arg$8203.call();
              final Func.U<β, α> f$7728 = $8204.mem1.call();
              return Thunk.<α>nested((Lazy<Lazy<α>>)(() -> f$7728.apply($8204.mem2)));
            });
  }
}
```

However, if I remove the `.call()` from ƒapp() this would compile (accordingly to IntelliJ code highlighting).

```
final public static class IArrowApply_$minus$gt implements CArrowApply<Func.U<?, ?>> {
  public IArrowApply_$minus$gt() {}
  final public static IArrowApply_$minus$gt it = new IArrowApply_$minus$gt();
  @Override final public <𝓒, 𝓑> Kind.B<Func.U<?, ?>, PreludeBase.TTuple2<Kind.B<Func.U<?, ?>, 𝓑, 𝓒>, 𝓑>, 𝓒> ƒapp() {
    return (Kind.B<Func.U<?, ?>, PreludeBase.TTuple2<Kind.B<Func.U<?, ?>, 𝓑, 𝓒>, 𝓑>, 𝓒>)IArrowApply_$minus$gt.<
          𝓒, 𝓑
        >app();
  }
//...
  final public static <α, β> Lazy<Func.U<PreludeBase.TTuple2<Func.U<β, α>, β>, α>> app() {
    return (Func.U<PreludeBase.TTuple2<Func.U<β, α>, β>, α>)((final Lazy<PreludeBase.TTuple2<Func.U<β, α>, β>> arg$8203) -> {
              final PreludeBase.TTuple2<Func.U<β, α>, β> $8204 = arg$8203.call();
              final Func.U<β, α> f$7728 = $8204.mem1.call();
              return Thunk.<α>nested((Lazy<Lazy<α>>)(() -> f$7728.apply($8204.mem2)));
            });
  }
}
```

I have read somewhere that this can be due to the fact that Frege doesn't have support for Functions being returned as objects. But is this really due to that as the fix is would be quite easy?

Am I missing something? If no, can I somehow work around this (maybe by declaring native Java code?

### PR DESCRIPTION
**Pull request by yuxuanchiadm**
Should be simplest fix for issue #323.

### CODE REVIEW

**Comment by Ingo60** [comment]
Congratulations, you must be the first person to dive into compiler internals that deep!

Would you mind to give a short explanation how you did this and why it works? This might help me and future maintainers to see what is going on.

**Comment by yuxuanchiadm** [comment]
So simply What's wrong before is Java generic not allow variant on subtype relation directly. So for type like:
```
TTuple2<A, B>
Func.U<A, B> <: Kind.B<Func.U<?, ?>, A, B>

Func.U<TTuple2<Func.U<A, B>>, A>, B>
```
We can't really coerce it to:
```
Kind.B<Func.U<?, ?>, TTuple2<Kind.B<Func.U<?, ?>, A, B>, A>, B>
```
Because there is no subtype relation between them. So we may need existential type to help us (aka wildcard in java). But we don't really want to do that. This will let code becomes more complicate.
What we need is just:
```
Func.U<A, B> == Kind.B<Func.U<?, ?>, A, B>
```
So we can encode our higher kinded types in java. So in short even we don't have something like "declaration site variance" in scala.
But we known it will be safe to do. We just need compiler to stop complain about that.
So luckily we have generic erase in java. That is we don't really have generic type in runtime. So we simply cast out type to Object then cast it back to what we want. This should only become an issue if we got lambda:
```
(Function<A, A>) (Object) a -> a
```
Luckily this not our case. And fix for this should be simple too.
So boring part comes. How do we do that? Did into compiler. Find code that we need to deal with. Actually I starting from InstanceCode.fr. First "instanceCode" then "instFun" etc. Finally took me several hours about tracing code path. I found "lambdaToKinded". Then tells it to cast to Object first. Last let's create PR :p

**Comment by yuxuanchiadm** [comment]
Off-topic thing.
Also I just noticed we are determining does some generated code have unchecked warning by folding through expr we generated. And try find pattern ```JCast Something```. That is cast something to Object. Instead store unchecked state like in ST monad. Then check it later should be better.

**Comment by Ingo60** [comment]
Brilliant!

The `JUnchecked` idea sounds great to me.

**Pull request merged**
