### PR TITLE
Remove warnings

### PR DESCRIPTION
**Pull request by catull**
Eliminate 2 warnings for unused import and unused variable.

### CODE REVIEW

**Comment by Ingo60** [comment]
Nice idea!

The situation is that development on the master branch is practically frozen for everything below `frege/compiler`. So I ask you to withdraw this PR and submit it anew against the **gen8** branch.
The following files should be ignored for the moment, though:

    frege/compiler/passes/GenCode.fr
    frege/compiler/gen/java/*.fr

To work with the gen8 branch, you'll need the `fregec.jar` contained in the latest eclipse plugin.

**Comment by Dierk** [comment]
catull, please note that for contribution to Frege core, we need your undisclosed name (at least internally) for legal reasons. IP clearing, copyright, you known...

**Comment by catull** [comment]
Good point, will retract the PR in master.

For legal matters ...

I opened up both real name and e-mail address in my profile, is it visible now?

I hereby accept that my contributions are bound to the "Frege BSD 3-clause license" as outlined in https://github.com/Frege/frege/wiki/Contributing-to-Frege section "Legal Issues (License)".

Do I have to sign a form ?

**Comment by catull** [comment]
The request does belong to this branch, will be moved to the gen8 branch.

**Comment by Dierk** [comment]
Yes, it is visible, thanks! 
Our current best understanding of this legal matter is that no form is needed but public agreement to the terms (expressed or implied) like you did above is sufficient. 
Thanks a lot for your contributions and welcome to the group!

**Pull request closed without merging**
