### PR TITLE
Fix #129 Remove MutableIO for mutable native types

### LINKED ISSUE #129: Problem with frege.java.Util.Properties
Some methods of `Properties` type seems to be incorrectly typed. For example, consider `load` method:

```frege
data Properties = native java.util.Properties where
  ...
  native load :: MutableIO Properties -> MutableIO Reader -> IO () throws IOException
               | MutableIO Properties -> MutableIO InputStream -> IO () throws IOException

```

It accepts only `MutableIO InputStream` but the language doesn't provide an ability to get `MutableIO InputStream` at all.

The same seems to be case with almost all methods of `Properties` type. I've discussed it with @Ingo60 in IRC and he thinks it may be caused due to problem with `frege-native-gen` (I'll check it eventually), so we maybe should rise another issue there.

The solution may be to simply remove `MutableIO` from `InputStream` (and maybe some another types) in method signatures of `Properties`. If the `Util` class was auto-generated and meant to be changed only by regeneration - we should fix the `frege-native-gen` first.

I am ready to provide some code samples about which I think they should compile and they are currently not.

### PR DESCRIPTION
**Pull request by mmhelloworld**
@Ingo60 @ForNeVer Please review.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I'll review that tonight, thank you.

**Comment by Ingo60** [comment]
Can you please recreate the request so that it would be merged with branch "work23"?

**Comment by mmhelloworld** [comment]
Sure, I will do that.

**Comment by ForNeVeR** [comment]
Well, I've set up a Vagrant box for experiments with Frege compiler and tried it with the following code [extracted from my playground project](https://github.com/ForNeVeR/jtray/blob/8ca14716e162e26670495ff39948ec96cd83b156/src/main/frege/Config.fr):

```frege
module me.fornever.jtray.Config where

import frege.java.Util (Properties)

data Config = Config { jenkinsUrl :: String,
                       jenkinsAuth :: Bool,
                       jenkinsLogin :: Maybe String,
                       jenkinsApiKey :: Maybe String }
derive Show Config

newProperties :: STMutable s Properties
newProperties = Properties.new ()

loadProperties :: InputStream -> IO (MutableIO Properties)
loadProperties stream = do
    properties <- newProperties
    Properties.load properties stream
    return properties

fromProperties :: Mutable s Properties -> ST s Config
fromProperties properties = do
    jenkinsAuth <- properties.getProperty "jenkins.auth" ""
    jenkinsUrl <- properties.getProperty "jenkins.url" ""
    jenkinsLogin <- properties.getProperty "jenkins.login" ""
    jenkinsApiKey <- properties.getProperty "jenkins.api_key" ""

    let auth = jenkinsAuth == "true"
    return $ Config { jenkinsUrl = jenkinsUrl,
                      jenkinsAuth = auth,
                      jenkinsLogin = if auth then Just jenkinsLogin else Nothing,
                      jenkinsApiKey = if auth then Just jenkinsApiKey else Nothing }

readConfig :: InputStream -> IO Config
readConfig stream = do
    properties <- loadProperties stream
    config <- fromProperties properties
    return config
```

This code indeed was uncompilable with old compiler version and successfully compiled with this patch applied. So I guess the bug has been fixed.

**Comment by mmhelloworld** [comment]
Pull request for the `work23` branch: https://github.com/Frege/frege/pull/131

**Comment by Ingo60** [comment]
As discussed, this one will not get merged into master. 
Rather, work23 will be merged into master later.

**Pull request closed without merging**
