### PR TITLE
Port of Haskell indexed lazy arrays

### PR DESCRIPTION
**Pull request by LGLO**
This is adaptation of GHC/Arr.hs but I decided to move all functions that take Array (or STArray) as first argument inside their namespace.
I have left only freezeSTArray and thawSTArray outside because I fell none of them belong to Array or STArray.
Also invalid documentation texts are fixed in Ix.fr.

### CODE REVIEW

**Comment by Ingo60** [comment]
Can we get some tests also?

**Comment by LGLO** [comment]
Yes, we can.
I think that regular 'property' QCs will be time waste during build.
So I think about 'once' unit tests for empty array case, undefined elements not evaluated unless necessary and few 'happy paths' - basically what I had in 'main' when I tested during development.
Which would be better?

**Comment by Ingo60** [comment]
Yes, but I think we should test in addition making arrays from lists and
back and also the behaviour of the various fold/map functions, as well as
the instances.

2015-11-21 11:05 GMT+01:00 Lech Głowiak <notifications@github.com>:

**Comment by LGLO** [comment]
Any feedback is appreciated before I move to STArray tests.

**Comment by LGLO** [comment]
listArray is an constructor which takes bounds of any Ix type and a list of values.
listArr is a helper function which calls listArray with (1, n) bounds (thus indicies = [1..n])

**Comment by Ingo60** [comment]
@LGLO while we are speaking of tests, have you noticed that some of the triple tests in Ix.fr sometimes break the CI build? For an example, see https://travis-ci.org/Frege/frege/jobs/90407465 Line 1221
(the test in and of itself is okay, its just that quickcheck fails to generate 100 test cases)

**Comment by Dierk** [comment]
So listArr is a listIntArray?
Btw: factory methods sometimes start with a "mk" prefix for "make". It is not a strong convention but when names are otherwise difficult to tell apart, it may help.

**Comment by LGLO** [comment]
I find numbering items from 1 natural so `listArr` ended as `mkNaturallyIndexedArray`.
`STArray` methods and related functions tests added, most of them in `once`.

**Comment by Ingo60** [comment]
Lech, are you going to use (!!) finally? Then please add this to the pull request, so that we can merge it. - Cheers, Ingo

**Comment by LGLO** [comment]
I just did. I think it's ready to merge.
Greetings!

**Comment by Ingo60** [comment]
Thank you, Lech!

**Pull request merged**
