### PR TITLE
Test with byaccj and pbyacc in addition to byacc

### PR DESCRIPTION
**Pull request by tkawachi**

### CODE REVIEW

**Comment by tkawachi** [comment]
https://travis-ci.org/Frege/frege/jobs/52545172#L1029-L1031
Hmm the workaround for #100 0513aebc35889dd383a7742661c30fe42f705b22 seems not working.

**Comment by Ingo60** [comment]
I don't understand this pull request. The byacc is working fine, isn't it?
I have changed the travis script so as to make it fail proof. (I hope)

By the way, why is it that on the main page the build is always shown as grey, i.e. unknown?

**Comment by Dierk** [comment]
It could be that it needs to be enabled in the github project settings. 

Dierk

sent from:mobile

**Comment by Ingo60** [comment]
Found it. There was an unknown branch mentioned. The image now shows the state of the latest build.

**Comment by tkawachi** [comment]
This pull request makes sure that every supported yacc variation doesn't causes an error. I don't know how these variatons are different, so this PR might be over kill if those are almost identical.

Sorry for unknown branch. I forgot to change it to proper one.

**Comment by Ingo60** [comment]
Ahh, now I understand.

This will not be necessary, though, because byaccj and pbyacc use the original byacc (= berkeley yacc) code and just extend it by adding support for generation of parsers in java or perl. But we don't use that extra functionality, we use only the basic one (i.e., generation of a parser in C).

So I ask you kindly to withdraw this pull request.

**Comment by tkawachi** [comment]
I see. Thank you for explanation of difference.

**Pull request closed without merging**
