### PR TITLE
Fixed compile error

### PR DESCRIPTION
**Pull request by tkawachi**

### CODE REVIEW

**Comment by tkawachi** [comment]
Hmm, it occasionally failed to compile.

````
E ./frege/Version.fr:1: Could not import package afrege.Prelude
    (java.lang.ClassNotFoundException: afrege.Prelude)
````

https://travis-ci.org/Frege/frege/jobs/52499249#L181-L182

**Comment by Ingo60** [comment]
I really have no idea why Dierk changed this?
Thanks for fixing!

As you see, I couldn't go to sleep without trying travis ..... :)

**Comment by tkawachi** [comment]
Yeah, it's really useful to catch such things.

**Comment by Dierk** [comment]
sorry, that must have been a total accident like "hitting a key when the cursor is in the wrong window".

I should have better checked my commit, though.
Dierk

**Pull request merged**
