### PR TITLE
Separate bootstrap fregec as fregec-bootstrap.jar from built one

### PR DESCRIPTION
**Pull request by tkawachi**
See https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html for .PHONY target.

### CODE REVIEW

**Comment by Ingo60** [comment]
Good point, but I want the makefile to be so simple that modifying it for use on Windows is easily done. (At present, one can do this by replacing the path separator character ':' with ';' and maintaining the YACC macro.)

But I believe the `nmake` tool doesn't support .PHONY, so this would be extra effort.

**Comment by tkawachi** [comment]
I see, I'm not familier with nmake...

**Comment by tkawachi** [comment]
But current makefile hardcode unix commands like `rm` or `mkdir`. It's better to make these variables.

**Comment by tkawachi** [comment]
I'll close this PR. Still it's better not to overwrite frege.jar IMO.

**Comment by Ingo60** [comment]
Yes, maybe you're right.

But see, I am very much used to how it works, and currently I just want to write the stuff for java8 compatibility and not worry about build tools.

So, let the makefile like it is for the time being, maybe we can enhance it later in a consolidation phase.

**Pull request closed without merging**
