### PR TITLE
fix a few small typos

### PR DESCRIPTION
**Pull request by ppelleti**
Found a few small typos in the documentation.  (And one in a compiler error message.)

### CODE REVIEW

**Comment by Dierk** [comment]
thanks for the contribution!

**Comment by Ingo60** [comment]
Haha, I bet Dierk is very unhappy not having found all typos himself :)

And I am unhappy because it turns out that the spell checker in TeXstudio  is apparently lacking. :)

**Comment by Dierk** [comment]
I'm happy to have found a brother in mind ;-)

**Comment by Ingo60** [comment]
I am truly (or: truely?) happy about this. Even if I am doing jokes.
In fact, I am so happy this is all in English, for

a) I am being auto-absolved as non-native speaker.
b) if it were in German, probably many more pre-government-imposed-orhography-reform "errors" would have to be corrected, and sometimes I would try to refuse it ....

**Pull request merged**
