### PR TITLE
Add compiler options to generate java gvars in ASCII chars

### PR DESCRIPTION
**Pull request by matil019**
This commit adds two compiler options:
- `-gvarsmath`:  uses mathematical chars (default, original behavior)
- `-gvarsascii`: uses ascii chars

### Details

`-gvarsascii` mangles type arguments `a`, `b`, `c`, ... into `A$GA`, `B$GA`, `C$GA`, ... instead of `𝓐`, `𝓑`, `𝓒`, ... etc.

I chose `$GA` as the suffix (stands for _G_ eneric _A_ rgument), and I consider they are as unlikely to conflict with other symbols as mathematical characters.

### Motivation

Use of Mathematical Bold Script Capital characters (e.g. "𝓐") leads to compatibility problems in some situations:

- Some environments can't display them properly (not important)
  - `tmux` + `vim` can't display them at all (appear blank), `gvim` can handle but ugly
- Some tools can't parse them (important)
  - `scalac` (Scala compiler) errors out against them
  - For example, `scalac B.scala A.java` parses `A.java` (but not compile it) and compiles `B.scala`.  
    `scalac` does this to compile `B.scala` even if there is a circular dependency between `A` and `B`.

This isn't really Frege's fault, but it would be much appreciated if Frege supports this compatibility feature.

### CODE REVIEW

**Comment by Ingo60** [comment]
I support this PR for the sad reasons given. However, I'd like to trigger this functionality with the existing -ascii flag. This turns off the USEUNICODE bit, so that we just have to check this one. 

I also suggest to use just uppercase letters for better readability. There will be no conflicts for single letters. For longer ones, conflicts may arise,  though. I suggest to use a prefix letter G in those cases.

**Comment by matil019** [comment]
@Ingo60 Thank you.

> However, I'd like to trigger this functionality with the existing -ascii flag. This turns off the USEUNICODE bit, so that we just have to check this one.
> 
> I also suggest to use just uppercase letters for better readability. There will be no conflicts for single letters.

All right, I'll implement as you suggested.

> I suggest to use a prefix letter G in those cases.

Do you mean that we generate single letters for this PR now (`A`, `B`, ...) and would change the code to prefix G (`GA`, `GB`, ...) when ever we encountered conflicts in future?

**Comment by matil019** [comment]
@Ingo60 Done.

**Comment by Ingo60** [comment]
I'm not sure exactly what the strategy was for finding a generics name. However, most of the time it comes out as a single letter. Here we are okay with using a single Latin letter. It could only collide with the module/class name. (Need to check what happens then?)
Longer sequences could only collide with existing names when it starts with one of T, D, C or I.

**Comment by matil019** [comment]
It seems the original code just translated a lower latin to a mathematic letter e.g. `a` -\> `𝓐`, `b` -\> `𝓑`. It should be ok because in Frege type variables must start with a lower latin letter.

> It could only collide with the module/class name. (Need to check what happens then?)

I think any non-trivial program ends up in a compilation error. An example I could come up with:

```java
public class Foo {
  public static class A { /* ... */ }

  // accessing members of `a` or returning it triggers a compilation error
  // in other words, compilation passes only if `a` is not used
  public static <A> A shadows(final A a) { /* ... */ }

  // error: cyclic inheritance involving A
  public static <A extends A> void extendsA(final A a) { /* ... */ }
}
```

workarounds in such cases would be avoiding `-ascii` or changing type variables in Frege code.

**Pull request merged**
